name: "ZAP"
on: #push 
 workflow_dispatch:

jobs: 
  zap_scan:
    runs-on: ubuntu-latest
    permissions: write-all
    name: zap
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # docker_name: 'owasp/zap2docker-stable'
          # docker_name: 'ghcr.io/zaproxy/zap-archives/zap2docker-stable:2.14.0'
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          # target: 'https://shjbs-sample.ddo.jp/top' # Change URL or IP of your target application
          # target: 'https://shjbs-sample.ddo.jp/top'
          target: 'https://juice-shop.herokuapp.com/#/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a -j -z "-config alert.maxInstaces=0"'

      - name: Output
        run: |
          cat report_json.json
